### PR TITLE
Custom graphical user interface(gui) 

### PR DESCRIPTION
**Pull request by Kushal-ghimire**
Hi Guys I have build test gui . Still we require some more components . Please review our sample gui format and provide some suggestions for improvement.

### CODE REVIEW

**Comment by Subashcoder** [comment]
Can make the GUI more interactive and also need to host on cloud

**Comment by KeshavGautam77** [comment]
GUI can be cloud-based and input output can be segregated.

**Comment by Nischal156** [comment]
we could make layout and spacing of the GUI components more visually appealing and cleaning and also reset button can be added.

**Comment by Subash049** [comment]
more Improvement can be done for  user interface by providing clear labels or instructions for team selection, reducing errors and enhancing usability.

**Comment by Kushal-ghimire** [comment]
Thank you guys for your suggestions, I will keep all the things in mind and improve in the next commit

**Comment by SonaThapa** [comment]
Needs more improvement in GUI.

**Pull request merged**
