### PR TITLE
Feature engineering verification and testing

### PR DESCRIPTION
**Pull request by Subashcoder**
Enhancing the feature engineering part.

Split the home_team and Away_team player stats.

Calculate the player xG, xA, xGC etc

Merge the data based on Match where home player and away player stats are on separate columns

### CODE REVIEW

**Comment by Kushal-ghimire** [comment]
we can gather more features like player stats from https://www.football-data.co.uk/ .

**Comment by Subash049** [comment]
We can use LSTM for the time series data

**Comment by SonaThapa** [comment]
Still some features are missing, some winning streak of the home team and away team can be added.

**Comment by KeshavGautam77** [comment]
Some features are still can be added something like
Team Av Shots Diff
Opponent Av Shots Diff
Team Result Indicator
Opponent Av Shots Inside Box Diff
Team Av Fouls Diff
Opponent Av Corners Diff
Opponent Av Pass Accuracy Diff 
Using this data we can gather more on team strength which will helps to predict the winning match

**Comment by Subashcoder** [comment]
Feature change wasn't approve by all the team members

**Comment by Subashcoder** [comment]
will be working on to add new features

**Comment by Nischal156** [comment]
it's important to provide clear and informative descriptions so that collaborators or future readers can understand the changes I've made. Here are some suggestions:

Overview: Providing a brief overview of the feature engineering task we are addressing. What problem are we trying to solve or what goal are we aiming for this project.

Approach: Describe the approach or methodology we used for feature engineering, like team form, player contribution, involvement of one player more than others.

Data Preprocessing: If applicable, discuss any data preprocessing steps that were taken before the feature engineering process.

Future Work: Outline any potential future work or improvements that could be made to the feature engineering process or the engineered features.

**Pull request closed without merging**
