### PR TITLE
Updating the features 

### PR DESCRIPTION
**Pull request by KeshavGautam77**
Please check the new features added

### CODE REVIEW

**Comment by Subash049** [comment]
all done

**Comment by Nischal156** [comment]
Feature Engineering: Added new features based on historical match data

Overview:
This pull request focuses on enhancing our football match prediction model by incorporating new features derived from historical match data.

Purpose:
The goal is to improve the predictive power of our model by capturing more nuanced information about past matches, which can help identify patterns and trends for better predictions.

**Comment by Subashcoder** [comment]
looks good, go on

**Comment by Kushal-ghimire** [comment]
Well done we are in the final stage of adding features. If there is any feature lagging then we can add later during optimization

**Comment by SonaThapa** [comment]
We are almost in final stage.

**Pull request closed without merging**
